KYRDTeam/Krystal-iOS

KyberNetwork/KyberNetwork/Configurations/Environments/Jsons/config_env_mainnet_test.json, KyberNetwork/KyberNetwork/Configurations/Environments/Jsons/config_env_production.json, KyberNetwork/KyberNetwork/Configurations/Environments/Jsons/config_env_staging.json, KyberNetwork/KyberNetwork/Configurations/Environments/Jsons/config_env_staging2.json
(cherry picked from commit be505f24e88f84e8f9addb7963791a675d8b82c1)
=> - update ens address

KyberNetwork/KyberNetwork/Screens/CommonViews/Contact/ContactTableView/KNContactTableView.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Balance/BalanceVC/Controller/HamburgerMenu/KNBalanceTabHamburgerMenuViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Settings/ListWalletsVC/Controller/KNListWalletsViewController.swift
(cherry picked from commit 60476abb93eff52710635c06a6cc650a3724cfeb)
=> Long press to copy wallet address in list wallets (hamburger menu + settings/manage wallet)

KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/CreateOrder/KNCreateLimitOrderViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/CreateOrder/KNCreateLimitOrderViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/CreateOrder/KNCreateLimitOrderViewModel.swift
(cherry picked from commit 052ae626dca990240716a48ac16d245aad372a51)
=> - add revert target rate to LO screen

KyberNetwork/KyberNetwork/Configurations/Environments/Jsons/config_env_production.json, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+Notification.swift, KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/RateCoordinator/KNRateCoordinator.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Notifications/Controller/KNListNotificationViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Balance/TokenChartVC/Controller/KNTokenChartViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/BuyKNC/KNCreateLimitOrderV2ViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/LimitOrderContainer/LimitOrderContainerViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/Cell/KNMarketTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/Cell/KNMarketTableViewCell.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/KNSelectMarketViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/KNSelectMarketViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/KNSelectMarketViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Coordinator/KNLimitOrderTabCoordinatorV2.swift, KyberNetwork/Tokens/Types/TokenObject.swift
- Switch account: Update wallet information in LO and hamburger view
- Change volume calculation to include both ETH and WETH
- Filter only supported tokens in Market view
- Change layout in Market view token cell
- Fix display data and sort in Market view
- Open KyberSwap with ETH -> token pair from Notification view with price trending
- Update UIs when market data updated
=> Fix several issues with LO v2

KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/KNSelectMarketViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/SelectMarket/KNSelectMarketViewController.xib
(cherry picked from commit 4d388bd53ce8038f7f688d3724d443a5064d1f77)
=> - fix 24h column alignment

KyberNetwork/KyberNetwork/Screens/SocialAccounts/Controllers/SignUp/KNSignUpViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/Backup/Controller/KNBackUpWalletViewController.swift
- only show skip button at last step of backing up wallet
=> [IOS-32][IOS-39] only show skip button at last step, round social sign up container with 5

KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/GasCoordinator/KNGasConfiguration.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Controller/KSendTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Coordinator/KNSendTokenViewCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/ViewModel/KNSendTokenViewModel.swift
- Increase gas default transfer to 180k
- Fix default gas limit for transfer token
- Separate logics of validating and sending transaction
=> [IOS-43] Wrong default gas limit for token, increase default transfer gas for token

KyberNetwork/KyberNetwork/Screens/Tabbars/Balance/BalanceVC/ViewModel/KWalletBalanceViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/ViewModel/KSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/LimitOrderContainer/LimitOrderContainerViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/LandingPage/Controller/KNLandingPageViewController.swift
- fix do not update quick tutorial status on swap and lo screen
=> [Fix] remove alway show quick tutorial on ropsten

KyberNetwork/KyberNetwork/Configurations/Environments/Sources/KNEnvironment.swift, KyberNetwork/Localization/en.lproj/Localizable.strings
- improve quick tutorial text in swap screen
=> [Improvement] Update staging expected rate endpoints

KyberNetwork/KyberNetwork/Coordinators/BalanceCoordinator/KNLoadBalanceCoordinator.swift
=> [IOS-111] Add fallback call in failure block when loading unsupported tokens

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/ViewModel/KSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Controller/KSendTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/ViewModel/KNSendTokenViewModel.swift
=> [IOS-120] Update src amount when gas price, gas limit, balance has changed

KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.xib, KyberNetwork/KyberNetwork/Screens/Transaction/History/Coordinator/KNHistoryCoordinator.swift, KyberNetwork/Localization/en.lproj/Localizable.strings, KyberNetwork/Localization/ko.lproj/Localizable.strings, KyberNetwork/Localization/vi.lproj/Localizable.strings, KyberNetwork/Localization/zh-Hans.lproj/Localizable.strings
=> [IOS-41] Add link to etherscan and enjinx to empty state view pending tx

KyberNetwork/Extensions/String.swift, KyberNetwork/KyberNetwork/Screens/Wallet/LandingPage/Controller/KNLandingPageViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/QRCode/Controller/KNWalletQRCodeViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/QRCode/Controller/KNWalletQRCodeViewController.xib, KyberNetwork/Localization/en.lproj/Localizable.strings, KyberNetwork/Localization/ko.lproj/Localizable.strings, KyberNetwork/Localization/vi.lproj/Localizable.strings, KyberNetwork/Localization/zh-Hans.lproj/Localizable.strings
- hide debug button in onboarding view
=> [IOS-128] Add info message about sending erc20 tokens

KyberNetwork/KyberNetwork/Screens/Wallet/LandingPage/Controller/KNLandingPageViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/LandingPage/Controller/KNLandingPageViewController.xib
(cherry picked from commit 51ad6025d63cda39b6c899ab6fc8a7e121ae08cf)
=> [Task] Remove debug button in landing page

KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/QRCode/Controller/KNWalletQRCodeViewController.xib, KyberNetwork/Localization/en.lproj/Localizable.strings, KyberNetwork/Localization/ko.lproj/Localizable.strings, KyberNetwork/Localization/vi.lproj/Localizable.strings, KyberNetwork/Localization/zh-Hans.lproj/Localizable.strings
- change left padding of address text
=> [IOS-128] Add underline char to text

KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/BuyKNC/KNCreateLimitOrderV2ViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Controllers/BuyKNC/KNCreateLimitOrderV2ViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/LimitOrder/Coordinator/KNLimitOrderServerCoordinator.swift
- Point learn more button to new url
=> [IOS-151] Improve LO error message format

KyberNetwork/KyberNetwork/Screens/Wallet/LandingPage/Coordinator/KNLandingPageCoordinator.swift, Podfile, Podfile.lock
=> [IOS-154] Fix issue with backup iPhone

KyberNetwork/KyberNetwork/Configurations/Environments/Sources/KNEnvironment.swift, KyberNetwork/KyberNetwork/Coordinators/BalanceCoordinator/KNLoadBalanceCoordinator.swift, KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/RateCoordinator/KNRateCoordinator.swift, KyberNetwork/KyberNetwork/Networking/External/KNGeneralProvider.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ChooseRateViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ChooseRateViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.xib, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/TransactionCollectionViewCell/KNHistoryTransactionCollectionViewCell.swift, KyberNetwork/Tokens/Types/TokenData.swift
- Update testnet path
- Fix bug in history view, swap confirm view and filter view
=> Improvement and fix bugs

KyberNetwork/KyberNetwork/Screens/CommonViews/Contact/ListContactView/KNListContactViewController.swift
Update style alert controller for delete contact
RE #KRYS-1101
=> [Settings] - Implement delete contact new UI

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ApproveTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ApproveTokenViewController.xib
**Reason**: wrong button title
**Fix**: update button title and refactor outlet and func name
RE #KRYS-1105
=> [Swap] Button name is wrong

KyberNetwork/KyberNetwork/Screens/Tabbars/Settings/ListWalletsVC/Coordinator/KNListWalletsCoordinator.swift
Update style show alert 
RE #KRYS-1090
=> [Settings] - Implement delete popup new UI

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/KyberNetwork/Extensions/UIColor+Kyber.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/CustomActionSheet/KNActionSheetAlertViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/CustomActionSheet/KNActionSheetAlertViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Settings/ListWalletsVC/Controller/KNListWalletsViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Settings/SettingsVC/Coordinator/KNSettingsCoordinator.swift
For backup and manage wallets
RE #KRYS-1126
=> [Settings] - Implement new UI of switch wallet popup

KyberNetwork/Assets.xcassets/secondaryColor.colorset/Contents.json, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnOverviewViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnSwapViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.xib, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Controller/KSendTokenViewController.xib
=> [KRYS-1603] Change pending transaction indicator (red dot indicator)

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
Disable approve button only when source token is current approvingToken 
RE #KRYS-1607
=> [KRYS-1607] disable switch token, select source token while approve tx is pending tx

.github/deploy, .github/workflows/ci.yml, .github/workflows/manual.yaml, .github/workflows/pr.yaml
* Added new "manual" workflow.
* This workflow will be able to specify the branch to build.
* Environment: Staging
* OTA Url: https://manual-ota.knstats.com
* Workflows will now not support concurrent builds (on the same branch).
* Workflows (ci, maunal) are independent, which means that if the CI workflow is building on the "main" branch, the Manual workflow can still build on the "main" branch without being destroyed.
=> Update CI Workflows

KyberNetwork/KyberNetwork/Coordinators/TransactionCoordinator/KNTransactionCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Storage/KNTokenStorage.swift
- avoid crash cause by un-use code
- Change interval when load rate in non eth chain
=> Change interval when load rate in non eth chain

KyberNetwork/KyberNetwork/Screens/CommonViews/Token/SearchToken/KNSearchTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Token/SearchToken/TableViewCell/KNSearchTokenTableViewCell.swift, KyberNetwork/KyberNetwork/Storage/KNSupportedTokenStorage.swift, KyberNetwork/Tokens/Types/TokenData.swift
+ Add code to sort priority listed token over the custom token: The listed token > custom token
+ Add code to check display icon of cell for custom token and listed token
=> [KRYS-1543] Improve displaying token 

KyberNetwork/KyberNetwork/Screens/Wallet/Create/Controller/KNCreateWalletViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/Create/Controller/KNCreateWalletViewController.xib
update text show 4 chains supported
=> [KRYS-1128] - Some small errors while create a new wallet - Change text and color only

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/TransactionStatus/KNTransactionStatusPopUp.swift
=> [KRYS-1167] Change buttons title

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.xib
=> [iOS] Hide swap info (rate, platform, fee, slippage, minimum received, price impact) when inputted amount is empty

KyberNetwork/KyberNetwork/Storage/KNSupportedTokenStorage.swift
also found bug for disable tokens and deleted tokens
RE #KRYS-1817
=> [iOS] Lost data of favorite token when switch chain and kill app

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewSummaryCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewTotalInfoCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift
=> [IOS] - [Summary] Update icon for hide/show button

KyberNetwork/KyberNetwork/Screens/CommonViews/Confirms/SwapConfirm/Controller/KConfirmSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Confirms/SwapConfirm/ViewModel/KConfirmSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
=> [iOS] Update the price-impact-missing text

KyberNetwork/KyberNetwork/Coordinators/RewardCoordinator/RewardCoordinator.swift
=> [IOS] - [Reward] Show message when user can't claim reward

KyberNetwork/KyberNetwork/Extensions/BigInt+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Coordinator/EarnCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ChooseRateViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ChooseRateViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/ViewModel/KSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Views/ChooseRateTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Views/ChooseRateTableViewCell.xib
=> [KRYS-1891] Show best rate and hide terrible rates at the client side

KyberNetwork/Foundation/StringFormatter.swift
=> [KRYS-1923] - [Summary] Add symbol to separate large number

KyberNetwork/KyberNetwork/Coordinators/RewardCoordinator/RewardCoordinator.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/TransactionStatus/KNTransactionStatusPopUp.swift
=> [IOS] Btn link to bsc scan doesn't work

KyberNetwork/KyberNetwork/Extensions/UIImageView+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Cells/EarnMenuTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnOverviewViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Coordinator/EarnCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewDepositTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewLiquidityPoolCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewMainViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewDepositViewController.swift, KyberNetwork/Tokens/Types/TokenData.swift, KyberNetwork/Tokens/Types/TokenObject.swift
=> [iOS] Some earn token display default token icon

.github/workflows/ci.yml, .github/workflows/manual.yaml
Signed-off-by: Viet-Anh Duong <vietanhs0817@gmail.com>
=> ci: Change macos version

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift
=> [iOS] I can swipe down to reload / resync token balances

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/ChooseRateViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Views/ChooseRateTableViewCell.xib
=> [IOS] Sometimes it shows Save 0$ instead of Best

KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+Notification.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator.swift, KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/RateCoordinator/KNRateCoordinator.swift
=> [iOS] Update call api flow for loading price in overview screen

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift
=> [KRYS-2045] App crashes when clicking to collapse NFT tab

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/WithdrawViewController.xib
=> [KRYS-1984] Missing info for (?) icon on Withdraw screen

KyberNetwork/KyberNetwork/Screens/CommonViews/Confirms/SwapConfirm/Controller/KConfirmSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Confirms/SwapConfirm/Controller/KConfirmSwapViewController.xib, KyberNetwork/KyberNetwork/Screens/CommonViews/Confirms/SwapConfirm/ViewModel/KConfirmSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/ViewModel/KSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/Settings/Types/Constants.swift
=> [iOS] Update swap confirmation

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/Foundation/StringFormatter.swift, KyberNetwork/KyberNetwork/Networking/Internal/KyberNetworkService.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/Cells/KrytalTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/Cells/KrytalTableViewCell.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/Cells/ReferralTiersCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/Cells/ReferralTiersCell.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/Coordinators/KrytalCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/KrytalViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/KrytalViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/ReferralTiersViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/ReferralTiersViewController.xib, KyberNetwork/Models/Krytal.swift, KyberNetwork/Settings/Types/Constants.swift
=> [KRYS-2049] - Dev screen Referral

KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/KrytalViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/KrytalViewController.xib
=> [iOS] - Update wording

.github/workflows/ci.yml, .github/workflows/manual.yaml
Signed-off-by: Viet-Anh Duong <vietanhs0817@gmail.com>
=> fix: Fastlane install failed cause by profile's path is empty

KyberNetwork/AppDelegate.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+Delegation.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+InSession.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Token/SearchToken/KNSearchTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/ViewModel/KSwapViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/AddTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Coordinator/AddTokenCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Settings/SettingsVC/Coordinator/KNSettingsCoordinator.swift, KyberNetwork/KyberNetwork/Storage/KNSupportedTokenStorage.swift, KyberNetwork/KyberSwap - Crypto ExchangeDebug.entitlements
=> [KRYS-1809] Support deeplink for swap

KyberNetwork/KyberNetwork/Extensions/NSObject+Kyber.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Token/SearchToken/KNSearchTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnSwapConfirmViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnSwapConfirmViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Krytal/ViewController/KrytalViewController.swift
=> [KRYS-2071] Update earn confirmation

KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/AddTokenViewController.swift
=> [iOS] Support Deep Link

KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Coordinator/EarnCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift
=> [iOS] Update error message

KyberNetwork/KyberNetwork/Extensions/BigInt+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewSummaryCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/KyberNetwork/Storage/BalanceStorage.swift, KyberNetwork/KyberNetwork/Storage/KNSupportedTokenStorage.swift, KyberNetwork/KyberNetwork/Storage/KNTrackerRateStorage.swift, KyberNetwork/Tokens/Types/TokenData.swift
=> [KRYS-2151] Subtract the hidden token balance from total balance

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.xib
=> [iOS] Fix bugs update UI slippage

KyberNetwork/KyberNetwork/Screens/Transaction/Send/Controller/KSendTokenViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/ViewModel/KNSendTokenViewModel.swift
=> [iOS] Remove ENS string in Recipient field for BSC

KyberNetwork/KyberNetwork/Screens/CommonViews/Contact/NewContact/KNNewContactViewController.swift
=> [KRYS-495] Keep Edit mode when edit address for edit contact screen

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.xib
=> [iOS] Change Text in Input textbox to place holder

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.swift
=> [iOS] Keep slippage default label text

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/GasFeeSelector/GasFeeSelectorPopupViewController.xib
=> [iOS] Missing '%' after lost focus textbox Input

KyberNetwork/KyberNetwork/Configurations/Environments/Sources/KNEnvironment.swift, KyberNetwork/KyberNetwork/Coordinators/TransactionCoordinator/KNTransactionCoordinator.swift, KyberNetwork/KyberNetwork/Networking/External/KNGeneralProvider.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/TransactionStatus/KNTransactionStatusPopUp.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnOverviewViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/DappCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Details/ViewModel/KNTransactionDetailsViewModel.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/TransactionCollectionViewCell/KNHistoryTransactionCollectionViewCell.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Coordinator/KNHistoryCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Controller/KSendTokenViewController.swift, KyberNetwork/KyberNetwork/Storage/EtherscanTransactionStorage.swift, KyberNetwork/Settings/Types/Constants.swift
=> [iOS] update history for cronos

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewDepositTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewLiquidityPoolCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewMainViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewMarketTableViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewChangeCurrencyViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewDepositViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Coordinator/OverviewCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/Settings/Types/Constants.swift, KyberNetwork/Tokens/Types/LPTokenModel.swift, KyberNetwork/Tokens/Types/TokenData.swift
=> [iOS] Missing currency unit before value

KyberNetwork/KyberNetwork/Extensions/Date+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Transaction/History/Controller/KNHistoryViewController.swift, KyberNetwork/KyberNetwork/Storage/EtherscanTransactionStorage.swift
=> [iOS] No token to filter on History

KyberNetwork/KyberNetwork/Screens/CommonViews/BaseController/KNBaseViewController.swift
=> [iOS] Support back gesture

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewMainViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/ChartViewController.swift
=> [iOS] Display asset price is incorrect for format rule

KyberNetwork/AppDelegate.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift
=> [iOS] Handle campaign link

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Cells/MultiSendAddressCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Cells/MultiSendCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/MultiSendViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/MultiSendCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Coordinator/KNSendTokenViewCoordinator.swift
=> [KRYS-2546-2549-2550] Fix bug

KyberNetwork/KyberNetwork/Screens/CommonViews/Popups/TransactionStatus/KNTransactionStatusPopUp.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Cells/MultiSendCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/MultiSendApproveViewController.xib, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/MultiSendCoordinator.swift
=> [KRYS-2581] Check watch wallet before send request

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/BuyCryptoCoordinator.swift
=> [iOS] update method check order

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/BuyCryptoCoordinator.swift
=> [iOS] refactor code

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/BuyCryptoCoordinator.swift
=> [iOS] refactor Bifinity

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/BifinityOrderViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/BuyCryptoViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/BuyCryptoCoordinator.swift
=> [iOS - Bifinity] Cancel request api when dismiss screen

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift
=> [iOS] Does not show [Buy Crypto] button after create new wallet

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/BuyCryptoViewController.swift
=> [iOS] Does not clean error after input valid value of Unit

KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/DappCoordinator.swift
=> Handle webview navigation

KyberNetwork/Extensions/UIViewController.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+InSession.swift, KyberNetwork/KyberNetwork/Coordinators/RewardCoordinator/RewardCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Coordinator/BuyCryptoCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift
=> [iOS] Can not stop Loading to continue app after change wallet

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift
=> [iOS] Display small amount

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift
=> [iOS] Show [Buy Crypto] at home screen for wallet which has not list in feature flag

KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.swift
=> [iOS][Earn] Do not show icon and "Coming soon" on Earn Screen

KyberNetwork/KyberNetwork/Screens/Wallet/Create/Controller/KNCreateWalletViewController.swift
=> [iOS] [Wallet] Missing string Arbitrum

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/KyberNetwork/Extensions/UICollectionView+register.swift, KyberNetwork/KyberNetwork/Extensions/UITableView+register.swift, KyberNetwork/KyberNetwork/Extensions/UIViewController+nib.swift
I think they will be helpful
Register cell with nib:
```
tableView.registerCellNib(CellClass.self)
```
Dequeue a cell: 
```
let cell = tableView.dequeueReusableCell(RewardTableViewCell.self, indexPath: indexPath)
```
Init ViewController: 
```
let vc = ViewController.instantiateFromNib()
```
=> Add some useful extensions

KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/RateCoordinator/KNRateCoordinator.swift, KyberNetwork/KyberNetwork/Extensions/String+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Cells/OverviewMainViewCell.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/ChartViewController.swift
=> [IOS] - [Summary] Token's price format is incorrect

KyberNetwork/KyberNetwork/Configurations/Environments/Sources/KNEnvironment.swift, KyberNetwork/KyberNetwork/Networking/External/ChainType.swift
=> [iOS][Supply] Wrong supply info

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift
=> [IOS] Total amount is double

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/KyberNetwork/Configurations/MixPanel/MixPanelManager.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator+InSession.swift, KyberNetwork/KyberNetwork/Coordinators/AppCoordinator/KNAppCoordinator.swift, Podfile, Podfile.lock
=> [iOS][Mix Panel] Analytics

KyberNetwork/KyberNetwork/Screens/Transaction/Details/ViewModel/KNTransactionDetailsViewModel.swift, KyberNetwork/KyberNetwork/Screens/Transaction/Send/Coordinator/KNSendTokenViewCoordinator.swift, KyberNetwork/Transactions/Types/TransactionHistory.swift
=> [iOS] update history transaction detail to address

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/KyberNetwork/Extensions/BigInt+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/KyberNetwork/Storage/BalanceStorage.swift, KyberNetwork/KyberNetwork/Storage/KNTrackerRateStorage.swift, KyberNetwork/KyberNetwork/Utilities/PairKey.swift, KyberNetwork/KyberNetwork/Utilities/ThreadProtectedObject.swift
**_Idea_**: 
- Synchronize reading/writing to objects to avoid multiple threads accessing to a same object at the same time. 
- Plus, cache number formatter.
=> Fix bug blocking UI when reloading data and starting up

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/AppDelegate.swift, KyberNetwork/Settings/Types/Constants.swift
#KRYS-2807
- https://github.com/KYRDTeam/krystal-mobile-enviroment/pull/1/files
=> Update Sentry config

KyberNetwork/KyberNetwork/Screens/Wallet/WalletsList/WalletsListViewController.swift, KyberNetwork/KyberNetwork/Screens/Wallet/WalletsList/WalletsListViewController.xib
=> [iOS] Hide wallet connect for solana

Podfile
https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185
https://github.com/CocoaPods/CocoaPods/issues/11355
=> Tmp fix the Cocoapod CDN outage

.github/workflows/unit-test.yml
Add support for unit test on PR.
=> Krys 3199/ios unit test

.github/workflows/ci-build.yml, .github/workflows/manual.yaml, .github/workflows/testflight.yaml, .github/workflows/unit-test.yml
Add support for pulling submodule in workflow
=> feat: support pulling submodule in workflow

.github/workflows/ci-build.yml, .github/workflows/manual.yaml, .github/workflows/testflight.yaml, .github/workflows/unit-test.yml
=> use new github pat

.github/workflows/ci-build.yml, .github/workflows/manual.yaml, .github/workflows/testflight.yaml, .github/workflows/unit-test.yml
Change secret name to KRYSTAL_BOT_GH_PAT
=> change secret name

.github/workflows/unit-test.yml
Update workflow to use stg instead of dev
=> feat: change env for unit test from dev to stg

KrystalUnitTests/History/BridgeOverView/BridgeTest.swift
Testing by wait for the response from server is likely testing the API, not the client code. If the API down, our tests will be failed. So it's not the correct way.
To test a function that calls some API, we have to mock the response. Should be discussed more in a meeting. So I will temporary comment these test cases to improve later.
=> Comment the not working test cases

.github/workflows/ci-build-debug.yml, fastlane/Fastfile
Support for build with debug mode.
=> feature: support manual trigger build with debug mode

KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/Controllers/OverviewMainViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Overview/ViewModels/OverviewMainViewModel.swift, KyberNetwork/KyberNetwork/Storage/BalanceStorage.swift
=> [KRYS-3859-3860] Fix issue

KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/BigInt+SwapSettings.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/Cells/SettingAdvancedModeFormCell.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/Cells/SettingBasicAdvancedFormCell.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/Cells/SettingBasicModeCell.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/ExpertModeWarningViewController.swift, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/ExpertModeWarningViewController.xib, KyberNetwork/KyberNetwork/Screens/CommonViews/TransactionSettings/TransactionSettingsViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/Coordinator/SwapV2Coordinator.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/ViewModels/SwapV2ViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/Views/SwapSummaryViewController.swift
=> [KRYS-4109-4110-4114-4107] Change logic gas limit from all rate api

KyberNetwork/Extensions/String.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/ViewModels/SwapPlatformItemViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/ViewModels/SwapV2ViewModel.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/SwapV2/Views/SwapV2ViewController.swift
Due to an infinite loop (isExpanding and platform rates)
=> Fix bug swap screen unstable

KyberNetwork/KyberNetwork/Screens/CommonViews/BaseController/BaseWalletOrientedViewController.swift
Hotfix/fix update allchain token balance
=> [iOS] fix bug fetch all token from all chain 

KyberNetwork.xcodeproj/project.pbxproj, KyberNetwork/Extensions/UIViewController.swift, KyberNetwork/KyberNetwork/Extensions/Date+Kyber.swift, KyberNetwork/KyberNetwork/Screens/Notification/ViewModels/NotificationItemViewModel.swift, KyberNetwork/KyberNetwork/Screens/Notification/Views/ListEmptyView.xib, KyberNetwork/KyberNetwork/Screens/Notification/Views/NotificationDetailViewController.swift, KyberNetwork/KyberNetwork/Screens/Notification/Views/NotificationDetailViewController.xib, KyberNetwork/KyberNetwork/Screens/Notification/Views/NotificationItemV2Cell.xib, KyberNetwork/KyberNetwork/Screens/Notification/Views/NotificationListViewController.swift, KyberNetwork/KyberNetwork/Screens/Notification/Views/NotificationV2ViewController.swift, KyberNetwork/KyberNetwork/Screens/Tabbars/Notification/ViewController/NotificationsViewController.xib, KyberNetwork/KyberNetwork/Utilities/DateFormatterUtil.swift, KyberNetwork/Localization/en.lproj/Localizable.strings, KyberNetwork/Resources/Strings.swift
Also resolve KRYS-4540, KRYS-4544, KRYS-4552
=> KRYS-4546: Add notification detail page

KyberNetwork/KyberNetwork/Screens/Wallet/WalletConnect/WalletConnectViewController.swift, KyberNetwork/KyberNetwork/Storage/EventManager/AppEventCenter.swift, KyberNetwork/Localization/en.lproj/Localizable.strings, KyberNetwork/Resources/Strings.swift, TransactionModule/TransactionModule/UI/TxSettings/Views/TransactionSettingAdvancedTab.swift
[Advanced Setting Tab](https://console.firebase.google.com/u/0/project/krystal---production/crashlytics/app/ios:com.kyrd.krystal.ios/issues/b76e844fd43eacd174f5fc287766947a?time=last-seven-days&sessionEventKey=1c8eac11cbc44aa29309840683027c65_1746468818387038889)
[Wallet Connect](https://console.firebase.google.com/u/0/project/krystal---production/crashlytics/app/ios:com.kyrd.krystal.ios/issues/555bbae9f92769bfd9ed043aac266c15?time=last-seven-days&sessionEventKey=8da0da01a2314c18a0f26e22a9b685aa_1745699498992213673)
=> Fix issues crash on crashlytics

TokenModule/TokenModule/Screens/TokenDetail/TokenDetailViewController.xib
Fix this [crash issue](https://console.firebase.google.com/u/0/project/krystal---production/crashlytics/app/ios:com.kyrd.krystal.ios/issues/7d77832d295b1739c7f71d3b3f36a899?time=last-seven-days&sessionEventKey=ab9921b8580e4e3c9ea04500815a6ae0_1754554006567434529)
=> Fix bug crash token detail

EarnModule/EarnModule/Cells/PendingRewardCell.swift, EarnModule/EarnModule/Cells/PendingRewardCell.xib
=> [Fixbug] Fix remain earnv2 issues

EarnModule/EarnModule/Cells/PendingRewardCell.swift, EarnModule/EarnModule/Cells/StakingPortfolioCell.xib, EarnModule/EarnModule/ViewControllers/EarnListViewController.swift, EarnModule/EarnModule/ViewModel/ClaimTxStatusPopupViewModel.swift, EarnModule/EarnModule/ViewModel/PendingRewardViewModel.swift, Services/Services/Core/Earn/EarnServices.swift
=> [Fix] Fix new feedbacks

EarnModule/EarnModule/Cells/EarnPoolPlatformCell.swift, EarnModule/EarnModule/Cells/EarnPoolPlatformCell.xib, EarnModule/EarnModule/Cells/EarnPoolViewCell.swift, EarnModule/EarnModule/ViewControllers/ClaimTxStatusPopup.swift, EarnModule/EarnModule/ViewControllers/EarnListViewController.swift, EarnModule/EarnModule/ViewControllers/StakingPortfolioViewController.swift, EarnModule/EarnModule/ViewModel/PendingRewardViewModel.swift
=> [Fix] Fix remaining earnv2 issue

EarnModule/EarnModule/ViewControllers/EarnListViewController.swift, EarnModule/EarnModule/ViewControllers/PendingRewardViewController.swift, EarnModule/EarnModule/ViewControllers/StakingPortfolioViewController.swift
=> [Fix] Fix some minor issues

EarnModule/EarnModule/Cells/PendingRewardCell.swift, EarnModule/EarnModule/StakingPortfolioViewModel.swift, EarnModule/EarnModule/ViewControllers/ClaimTxStatusPopup.xib, EarnModule/EarnModule/ViewControllers/PendingRewardViewController.swift, EarnModule/EarnModule/ViewControllers/PlatformFilterViewController.swift, EarnModule/EarnModule/ViewControllers/StakingPortfolioViewController.swift, EarnModule/EarnModule/ViewModel/PendingRewardViewModel.swift, Services/Services/Models/PortfolioStaking.swift
=> [Improvement] Improvement earnv2

TransactionModule/TransactionModule/UI/Approve/ApproveTokenViewController.swift, TransactionModule/TransactionModule/UI/Approve/ApproveTokenViewModel.swift
=> [iOS] update gas limit for tx approve 
